### ISSUE TITLE
Task03 FilteredPage

### ISSUE THREAD

**Issue by positivebrandon** [codestates/noti-client#5]
**ISSUE**

-  Group: client

- Type: feature

- Detail: Create  Filtered Page Component

**TODO**

- [x] Save card list
- [x]  Route product detail page
- [x] Css(card list)
